ecmwf0.1_pattern: './%Y/%j/ECMWF_FORECAST_0100_%Y%m%d%H%M_10U_10V.nc'
ww3_pattern: './%Y/FIELD_NC/LOPS_WW3-GLOB-30M_%Y%m.nc'
l1c_iw_version: '0.1'
iw_outputdir: none
data_dir: '../assests/'
wv_outputdir: none