#!/usr/bin/env bash
#PBS -l walltime=06:40:00
#PBS -N L1B-Ciw
#PBS -m n

# original memory was 1g but with ww3 spectra + SAR spectra it should be 2Go, now set in prun call
# memory needed if about 4Go for 17.7km tiles and 14Go for 2km tiles, 71 running in parallel on datarmor
echo start
# inputs

#$1 str l1bsafe
#$2 str version of the run: 1.5 for instance
#$3 str outputdir
#$4 str path of python micromamba env (without /bin/python)
#$5 str overwrite [optional]
#$6 str ww3spectra [optional]
myvariable=$(whoami)
. /appli/anaconda/latest/etc/profile.d/conda.sh
#conda activate /home/datawork-cersat-public/cache/project/mpc-sentinel1/workspace/mamba/envs/xsar_oct22
#conda activate /home/datawork-cersat-public/project/mpc-sentinel1/workspace/mamba/envs/l1bprocmars23
#echo 'which python?'
#which python

exe=do_IW_L1C_SAFE_from_L1B_SAFE

SHORT=s:,v:,o:,r,w,e:,h
LONG=safe:,version:,outputdir:,redo,ww3spectra,env:,help
OPTS=$(getopt -a -n do_IW_L1C_SAFE_from_L1B_SAFE --options $SHORT --longoptions $LONG -- "$@")
eval set -- "$OPTS"
help()
{
    echo "Usage: do_IW_L1C_SAFE_from_L1B_SAFE [ -s | --safe ]
               [ -o | --outputdir ]
               [ -v | --version ]
               [ -w | --ww3spectra ]
               [ -r | --redo ]
               [ -e | --env ]
               [ -h | --help  ]"
    exit 2
}
while :
do
  echo 'dollars=' $1 $2
  case "$1" in
    -s | --safe )
      safe="$2"
      shift 2
      ;;
    -v | --version )
      version="$2"
      shift 2
      ;;
    -o | --outputdir )
      outputdir="$2"
      shift 2
      ;;
    -r | --redo )
      redo="true"
      shift  #past argument
      ;;
    -w | --ww3spectra)
      ww3spectra="true"
      shift  #past argument
      ;;
    -e | --env )
      env="$2"
      shift 2
      ;;
    -h | --help)
      help
      ;;
    --)
      shift;
      break
      ;;
    *)
      echo "Unexpected option: $1"
      ;;
  esac
done

echo "redo: "$redo
echo "outputdir: "$outputdir
echo "version: "$version
echo "safe: "$safe
echo "ww3spectra: "$ww3spectra
echo "env: "$env
options='--l1bsafe '$safe" --outputdir "$outputdir" --version "$version
if [ -z "$ww3spectra" ]
then
    echo 'ww3 spectra not added'
  else
    options=$options" --ww3spectra "
fi
#if [ "$redo" == "--overwrite" ];
if [ ! -z "$redo" ]
then
    options=$options" --overwrite "
  else
    echo 'no overwritting of L1B files'
fi

echo 'final options: '$options
conda activate $env
which python
$exe $options










#echo 'number of arguments' $#
#echo 'fourth arg' $4
#if [ "$4" == "--overwrite" ]; then
#  echo 'overwrite is ON'
#  $exe  --l1bsafe $1 --version $2 --outputdir $3 --overwrite
#else
#  echo 'overwrite is OFF'
#  $exe  --l1bsafe $1 --version $2 --outputdir $3
#fi
