#!/usr/bin/env bash
#PBS -l walltime=20:40:00
#PBS -l mem=700m
#PBS -N L1B-L1Cwv
#PBS -m n

echo start
# inputs
#$1 str l1bsafe
#$2 str version of the run: 1.5 for instance
#$3 outputdir
myvariable=$(whoami)
. /appli/anaconda/latest/etc/profile.d/conda.sh
#conda activate /home/datawork-cersat-public/cache/project/mpc-sentinel1/workspace/mamba/envs/xsar_oct22
conda activate /home/datawork-cersat-public/project/mpc-sentinel1/workspace/mamba/envs/l1bprocmars23
echo 'which python?'
which python

exe=do_WV_L1C_SAFE_from_L1B_SAFE

$exe --overwrite  --l1bsafe $1 --version $2 --outputdir $3
